from .recipe_list import RecipeListViewHome,RecipeListViewCategory,RecipeListViewSearch,RecipeListViewHomeApi,RecipeListViewTags
from .recipe_detail import RecipeDetail,RecipeDetailApi
from .theory import Theory